# Generated by Django 5.0.6 on 2026-05-20 13:53

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support_telegram",
                    models.CharField(default="@jip_support", max_length=100),
                ),
                ("support_phone", models.CharField(blank=True, max_length=30)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin kontaktlari",
                "verbose_name_plural": "Admin kontaktlari",
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz_latin", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255)),
                ("description_uz_latin", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="gifts/")),
                (
                    "points_cost",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        blank=True, help_text="Bo'sh = cheksiz", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sovg'a",
                "verbose_name_plural": "Sovg'alar",
                "ordering": ["order", "points_cost"],
            },
        ),
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_uz", models.CharField(max_length=200)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                ("description_uz", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("stream_url", models.URLField()),
                ("starts_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Rejalashtirilgan"),
                            ("live", "Efirda"),
                            ("finished", "Tugagan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="livestreams/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Jonli efir",
                "verbose_name_plural": "Jonli efirlar",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReminderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("text_uz", models.TextField(blank=True)),
                ("text_ru", models.TextField(blank=True)),
                (
                    "send_day",
                    models.IntegerField(
                        default=1, help_text="Oyning qaysi kuni (1-28)"
                    ),
                ),
                ("send_hour", models.IntegerField(default=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Oylik eslatma sozlamalari",
                "verbose_name_plural": "Oylik eslatma sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                ("text_uz", models.TextField()),
                ("text_ru", models.TextField()),
                (
                    "pdf_uz",
                    models.FileField(blank=True, null=True, upload_to="privacy/"),
                ),
                (
                    "pdf_ru",
                    models.FileField(blank=True, null=True, upload_to="privacy/"),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Maxfiylik siyosati",
                "verbose_name_plural": "Maxfiylik siyosatlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_uz", models.CharField(max_length=200)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                ("text_uz", models.TextField(blank=True)),
                ("text_ru", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="promotions/"),
                ),
                ("link", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Promotsiya banneri",
                "verbose_name_plural": "Promotsiya bannerlari",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Do'kon nomi")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yuridik nom"
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(verbose_name="To'liq manzil")),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="stores/logos/"),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="Komissiya foizi",
                    ),
                ),
                ("contract_signed_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Do'kon",
                "verbose_name_plural": "Do'konlar",
                "ordering": ["region__code", "name"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True, unique=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("santenik", "Santenik"), ("sotuvchi", "Sotuvchi")],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("uz_latin", "O'zbek (Lotin)"), ("ru", "Русский")],
                        default="uz_latin",
                        max_length=15,
                    ),
                ),
                ("privacy_accepted", models.BooleanField(default=False)),
                ("last_message_sent_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_bot_at", models.DateTimeField(blank=True, null=True)),
                ("promo_failed_attempts", models.IntegerField(default=0)),
                ("promo_block_stage", models.IntegerField(default=0)),
                ("promo_blocked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram foydalanuvchisi",
                "verbose_name_plural": "Telegram foydalanuvchilari",
                "ordering": ["-created_at"],
                "permissions": [
                    ("send_region_messages", "Can send region broadcasts"),
                    ("change_user_type_call_center", "Call Center: change user type"),
                    ("add_seller_points", "Can add points to seller"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UzDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100)),
                ("name_uz", models.CharField(max_length=120)),
                ("name_ru", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Tuman",
                "verbose_name_plural": "Tumanlar",
                "ordering": ["region__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="UzRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name_uz", models.CharField(max_length=120)),
                ("name_ru", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Viloyat",
                "verbose_name_plural": "Viloyatlar",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="VideoInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_uz", models.CharField(max_length=200)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                (
                    "video_uz",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                (
                    "video_ru",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                (
                    "file_id_uz",
                    models.CharField(
                        blank=True, help_text="Telegram file_id (cache)", max_length=255
                    ),
                ),
                ("file_id_ru", models.CharField(blank=True, max_length=255)),
                (
                    "thumb_uz",
                    models.ImageField(
                        blank=True, null=True, upload_to="videos/thumbs/"
                    ),
                ),
                (
                    "thumb_ru",
                    models.ImageField(
                        blank=True, null=True, upload_to="videos/thumbs/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Yo'riqnoma video",
                "verbose_name_plural": "Yo'riqnoma videolari",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text_uz", models.TextField(blank=True)),
                ("text_ru", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="broadcasts/"),
                ),
                (
                    "user_type_filter",
                    models.CharField(
                        blank=True,
                        choices=[("santenik", "Santenik"), ("sotuvchi", "Sotuvchi")],
                        max_length=20,
                    ),
                ),
                (
                    "language_filter",
                    models.CharField(
                        blank=True,
                        choices=[("uz_latin", "O'zbek (Lotin)"), ("ru", "Русский")],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("queued", "Navbatda"),
                            ("sending", "Jo'natilmoqda"),
                            ("completed", "Tugadi"),
                            ("failed", "Xatolik"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.store",
                    ),
                ),
                (
                    "region_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.uzregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mass-rassilka",
                "verbose_name_plural": "Mass-rassilka'lar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalGift",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name_uz_latin", models.CharField(max_length=255)),
                ("name_ru", models.CharField(blank=True, max_length=255)),
                ("description_uz_latin", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("image", models.TextField(max_length=100)),
                (
                    "points_cost",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        blank=True, help_text="Bo'sh = cheksiz", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sovg'a",
                "verbose_name_plural": "historical Sovg'alar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiveStream",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title_uz", models.CharField(max_length=200)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                ("description_uz", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("stream_url", models.URLField()),
                ("starts_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Rejalashtirilgan"),
                            ("live", "Efirda"),
                            ("finished", "Tugagan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Jonli efir",
                "verbose_name_plural": "historical Jonli efirlar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPromotion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title_uz", models.CharField(max_length=200)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                ("text_uz", models.TextField(blank=True)),
                ("text_ru", models.TextField(blank=True)),
                ("image", models.TextField(blank=True, max_length=100, null=True)),
                ("link", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Promotsiya banneri",
                "verbose_name_plural": "historical Promotsiya bannerlari",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="QRCodeBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Batch nomi")),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "points_per_code",
                    models.IntegerField(
                        default=50,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("processing", "Generatsiya jarayonida"),
                            ("completed", "Tayyor"),
                            ("failed", "Xatolik"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(blank=True, null=True, upload_to="batches/"),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("not_shipped", "Hali jo'natilmagan"),
                            ("shipped", "Jo'natildi"),
                            ("delivered", "Yetkazib berildi"),
                        ],
                        db_index=True,
                        default="not_shipped",
                        max_length=20,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Agent ismi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batch'lar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "hash_code",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "serial_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("image_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "points",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("is_scanned", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qr_codes",
                        to="core.qrcodebatch",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qr_codes",
                        to="core.store",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "santenik"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scanned_qrcodes",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skretch-karta (QR)",
                "verbose_name_plural": "Skretch-kartalar",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalQRCodeBatch",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Batch nomi")),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "points_per_code",
                    models.IntegerField(
                        default=50,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("processing", "Generatsiya jarayonida"),
                            ("completed", "Tayyor"),
                            ("failed", "Xatolik"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("zip_file", models.TextField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("not_shipped", "Hali jo'natilmagan"),
                            ("shipped", "Jo'natildi"),
                            ("delivered", "Yetkazib berildi"),
                        ],
                        db_index=True,
                        default="not_shipped",
                        max_length=20,
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Agent ismi"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Batch",
                "verbose_name_plural": "historical Batch'lar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "sotuvchi"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_stores",
                to="core.telegramuser",
                verbose_name="Egasi (sotuvchi)",
            ),
        ),
        migrations.CreateModel(
            name="SellerPointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("manual_add", "Admin qo'shdi"),
                            ("sales_bonus", "Sotuv bonusi"),
                            ("correction", "Tuzatish"),
                            ("penalty", "Jarima"),
                        ],
                        default="manual_add",
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Musbat — qo'shish, manfiy — ayirish"
                    ),
                ),
                (
                    "sales_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ushbu tranzaksiya qaysi sotuvga bog'liq (ixtiyoriy)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seller_transactions",
                        to="core.store",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "sotuvchi"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seller_transactions",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sotuvchi tranzaksiyasi",
                "verbose_name_plural": "Sotuvchi tranzaksiyalari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegionMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.broadcastmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_logs",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rassilka log",
                "verbose_name_plural": "Rassilka loglari",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCodeScanAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=False)),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_attempts",
                        to="core.qrcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_attempts",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR skanlash urinishi",
                "verbose_name_plural": "QR skanlash urinishlari",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCodeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_code", models.CharField(blank=True, max_length=255)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bot", "Bot"),
                            ("webapp", "WebApp"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_attempts",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo-kod urinishi",
                "verbose_name_plural": "Promo-kod urinishlari",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oylik eslatma logi",
                "verbose_name_plural": "Oylik eslatma loglari",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyPromoTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                ("order", models.PositiveIntegerField(db_index=True)),
                ("scanned_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_ticket",
                        to="core.qrcode",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_tickets",
                        to="core.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_promo_tickets",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oylik lotereya bileti",
                "verbose_name_plural": "Oylik lotereya biletlari",
            },
        ),
        migrations.CreateModel(
            name="LiveStreamWinner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prize_text_uz", models.CharField(max_length=255)),
                ("prize_text_ru", models.CharField(blank=True, max_length=255)),
                ("announced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winners",
                        to="core.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestream_wins",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Efir g'olibi",
                "verbose_name_plural": "Efir g'oliblari",
                "ordering": ["-announced_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSellerPointsTransaction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("manual_add", "Admin qo'shdi"),
                            ("sales_bonus", "Sotuv bonusi"),
                            ("correction", "Tuzatish"),
                            ("penalty", "Jarima"),
                        ],
                        default="manual_add",
                        max_length=20,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Musbat — qo'shish, manfiy — ayirish"
                    ),
                ),
                (
                    "sales_amount_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ushbu tranzaksiya qaysi sotuvga bog'liq (ixtiyoriy)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.store",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"user_type": "sotuvchi"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sotuvchi tranzaksiyasi",
                "verbose_name_plural": "historical Sotuvchi tranzaksiyalari",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalQRCode",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=255)),
                ("hash_code", models.CharField(db_index=True, max_length=32)),
                ("serial_number", models.CharField(db_index=True, max_length=50)),
                ("image_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "points",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, editable=False)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("is_scanned", models.BooleanField(db_index=True, default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.qrcodebatch",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.store",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"user_type": "santenik"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Skretch-karta (QR)",
                "verbose_name_plural": "historical Skretch-kartalar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMonthlyPromoTicket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                ("order", models.PositiveIntegerField(db_index=True)),
                ("scanned_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qr_code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.qrcode",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Oylik lotereya bileti",
                "verbose_name_plural": "historical Oylik lotereya biletlari",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGiftRedemption",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "So'rov qabul qilindi"),
                            ("approved", "Mahsulot tayyorlash bosqichida"),
                            ("sent", "Yetkazib berishga topshirildi"),
                            ("completed", "Yetkazib berildi"),
                            ("rejected", "Bekor qilindi"),
                            ("not_received", "Foydalanuvchi olmadi"),
                            ("cancelled_by_user", "Foydalanuvchi bekor qildi"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, editable=False)),
                ("admin_notes", models.TextField(blank=True)),
                ("user_confirmed", models.BooleanField(default=False)),
                ("user_comment", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.gift",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"user_type": "santenik"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sovg'a buyurtmasi",
                "verbose_name_plural": "historical Sovg'a buyurtmalari",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="GiftRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "So'rov qabul qilindi"),
                            ("approved", "Mahsulot tayyorlash bosqichida"),
                            ("sent", "Yetkazib berishga topshirildi"),
                            ("completed", "Yetkazib berildi"),
                            ("rejected", "Bekor qilindi"),
                            ("not_received", "Foydalanuvchi olmadi"),
                            ("cancelled_by_user", "Foydalanuvchi bekor qildi"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("user_confirmed", models.BooleanField(default=False)),
                ("user_comment", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="core.gift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "santenik"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_redemptions",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sovg'a buyurtmasi",
                "verbose_name_plural": "Sovg'a buyurtmalari",
                "ordering": ["-requested_at"],
                "permissions": [
                    (
                        "change_status_call_center",
                        "Call Center: change redemption status",
                    ),
                    (
                        "change_status_agent",
                        "Agent: change status (sent/completed only)",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.uzdistrict",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stores",
                to="core.uzdistrict",
            ),
        ),
        migrations.AddField(
            model_name="uzdistrict",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="core.uzregion",
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.uzregion",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stores",
                to="core.uzregion",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalTelegramUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[("santenik", "Santenik"), ("sotuvchi", "Sotuvchi")],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("uz_latin", "O'zbek (Lotin)"), ("ru", "Русский")],
                        default="uz_latin",
                        max_length=15,
                    ),
                ),
                ("privacy_accepted", models.BooleanField(default=False)),
                ("last_message_sent_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_bot_at", models.DateTimeField(blank=True, null=True)),
                ("promo_failed_attempts", models.IntegerField(default=0)),
                ("promo_block_stage", models.IntegerField(default=0)),
                ("promo_blocked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.uzdistrict",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.uzregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Telegram foydalanuvchisi",
                "verbose_name_plural": "historical Telegram foydalanuvchilari",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStore",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Do'kon nomi")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yuridik nom"
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(verbose_name="To'liq manzil")),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("logo", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        verbose_name="Komissiya foizi",
                    ),
                ),
                ("contract_signed_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"user_type": "sotuvchi"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.telegramuser",
                        verbose_name="Egasi (sotuvchi)",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.uzdistrict",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.uzregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Do'kon",
                "verbose_name_plural": "historical Do'konlar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBroadcastMessage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text_uz", models.TextField(blank=True)),
                ("text_ru", models.TextField(blank=True)),
                ("image", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "user_type_filter",
                    models.CharField(
                        blank=True,
                        choices=[("santenik", "Santenik"), ("sotuvchi", "Sotuvchi")],
                        max_length=20,
                    ),
                ),
                (
                    "language_filter",
                    models.CharField(
                        blank=True,
                        choices=[("uz_latin", "O'zbek (Lotin)"), ("ru", "Русский")],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("queued", "Navbatda"),
                            ("sending", "Jo'natilmoqda"),
                            ("completed", "Tugadi"),
                            ("failed", "Xatolik"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store_filter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.store",
                    ),
                ),
                (
                    "region_filter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.uzregion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Mass-rassilka",
                "verbose_name_plural": "historical Mass-rassilka'lar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="qrcodebatch",
            index=models.Index(
                fields=["status", "-created_at"], name="core_qrcode_status_38fe46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcodebatch",
            index=models.Index(
                fields=["store", "delivery_status"],
                name="core_qrcode_store_i_a15fa8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qrcodebatch",
            unique_together={("name", "store")},
        ),
        migrations.AddIndex(
            model_name="sellerpointstransaction",
            index=models.Index(
                fields=["seller", "-created_at"], name="core_seller_seller__fea8e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerpointstransaction",
            index=models.Index(
                fields=["store", "-created_at"], name="core_seller_store_i_abae5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regionmessagelog",
            index=models.Index(
                fields=["broadcast", "-sent_at"], name="core_region_broadca_782f73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcodescanattempt",
            index=models.Index(
                fields=["user", "-attempted_at"], name="core_qrcode_user_id_95cad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["store", "is_scanned"], name="core_qrcode_store_i_4b4d82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["batch", "is_scanned"], name="core_qrcode_batch_i_e5a5b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["is_scanned", "scanned_at"],
                name="core_qrcode_is_scan_09b98d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promocodeattempt",
            index=models.Index(
                fields=["user", "-attempted_at"], name="core_promoc_user_id_53381c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocodeattempt",
            index=models.Index(
                fields=["is_successful", "-attempted_at"],
                name="core_promoc_is_succ_6441bc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyreminderlog",
            unique_together={("user", "month")},
        ),
        migrations.AddIndex(
            model_name="monthlypromoticket",
            index=models.Index(
                fields=["month", "user"], name="core_monthl_month_55a4ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlypromoticket",
            index=models.Index(
                fields=["month", "store"], name="core_monthl_month_325dda_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlypromoticket",
            constraint=models.UniqueConstraint(
                fields=("order",), name="uniq_ticket_order_global"
            ),
        ),
        migrations.AddIndex(
            model_name="giftredemption",
            index=models.Index(
                fields=["status", "-requested_at"], name="core_giftre_status_47093a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uzdistrict",
            unique_together={("region", "code")},
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["is_active", "region"], name="core_store_is_acti_7cd889_idx"
            ),
        ),
    ]
