# Generated by Django 5.0.1 on 2025-12-05 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('user_type_filter', models.CharField(blank=True, choices=[('electrician', 'Электрик'), ('seller', 'Продавец')], max_length=20, null=True, verbose_name='Фильтр по типу пользователя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sending', 'Отправляется'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_users', models.IntegerField(default=0, verbose_name='Всего пользователей')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало отправки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='gifts/', verbose_name='Изображение')),
                ('points_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость в баллах')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
                'ordering': ['points_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('electrician', 'Электрик'), ('seller', 'Продавец')], max_length=20, null=True)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('last_message_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение отправлено')),
                ('blocked_bot_at', models.DateTimeField(blank=True, null=True, verbose_name='Заблокировал бота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code_type', models.CharField(choices=[('electrician', 'Электрик (E-)'), ('seller', 'Продавец (D-)')], max_length=20)),
                ('hash_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_qrcodes', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'QR-код',
                'verbose_name_plural': 'QR-коды',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('completed', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Запрошено')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('delivery_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус доставки')),
                ('user_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено пользователем')),
                ('user_comment', models.TextField(blank=True, verbose_name='Комментарий пользователя')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.gift', verbose_name='Подарок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_redemptions', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получение подарка',
                'verbose_name_plural': 'Получения подарков',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_attempts', to='core.qrcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_attempts', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Попытка сканирования',
                'verbose_name_plural': 'Попытки сканирования',
                'ordering': ['-attempted_at'],
                'unique_together': {('user', 'qr_code')},
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['code'], name='core_qrcode_code_457661_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['hash_code'], name='core_qrcode_hash_co_15c174_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['is_scanned'], name='core_qrcode_is_scan_4074ad_idx'),
        ),
    ]
