# Generated by Django 5.0.1 on 2025-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='hash_code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
