# Generated by Django 5.0.1 on 2025-12-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_qrcode_hash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='serial_number',
            field=models.CharField(db_index=True, default=1, max_length=50, unique=True, verbose_name='Серийный номер'),
            preserve_default=False,
        ),
    ]
