# Generated by Django 5.0.1 on 2025-12-05 12:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_qrcode_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yuborish', 'verbose_name_plural': 'Yuborishlar'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['points_cost', 'name'], 'verbose_name': "Sovg'a", 'verbose_name_plural': "Sovg'alar"},
        ),
        migrations.AlterModelOptions(
            name='giftredemption',
            options={'ordering': ['-requested_at'], 'verbose_name': "Sovg'a olish", 'verbose_name_plural': "Sovg'a olishlar"},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-generated_at'], 'verbose_name': 'QR-kod', 'verbose_name_plural': 'QR-kodlar'},
        ),
        migrations.AlterModelOptions(
            name='qrcodescanattempt',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Skanerlash urinishi', 'verbose_name_plural': 'Skanerlash urinishlari'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram foydalanuvchi', 'verbose_name_plural': 'Telegram foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz_latin', "O'zbek (Lotin)"), ('uz_cyrillic', "O'zbek (Kirill)"), ('ru', 'Русский')], default='uz_latin', max_length=15, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='failed_count',
            field=models.IntegerField(default=0, verbose_name='Xatolar'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='message_text',
            field=models.TextField(verbose_name='Xabar matni'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='sent_count',
            field=models.IntegerField(default=0, verbose_name='Yuborildi'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yuborish boshlangan'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Yuborish kutilmoqda'), ('sending', 'Yuborilmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Yuborish nomi'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='total_users',
            field=models.IntegerField(default=0, verbose_name='Jami foydalanuvchilar'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='user_type_filter',
            field=models.CharField(blank=True, choices=[('electrician', 'Elektrik'), ('seller', 'Sotuvchi')], max_length=20, null=True, verbose_name="Foydalanuvchi turi bo'yicha filtr"),
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(upload_to='gifts/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='points_cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ballar narxi'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Administrator eslatmalari'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Yuborish kutilmoqda'), ('sent', 'Yuborildi'), ('delivered', 'Yetkazildi')], default='pending', max_length=20, verbose_name='Yetkazib berish holati'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.gift', verbose_name="Sovg'a"),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qayta ishlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="So'ralgan vaqt"),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('completed', 'Bajarildi')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_redemptions', to='core.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='user_comment',
            field=models.TextField(blank=True, verbose_name='Foydalanuvchi sharhi'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='user_confirmed',
            field=models.BooleanField(default=False, verbose_name='Foydalanuvchi tomonidan tasdiqlandi'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code_type',
            field=models.CharField(choices=[('electrician', 'Elektrik (E-)'), ('seller', 'Sotuvchi (D-)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Seriya raqami'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='blocked_bot_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Botni bloklagan vaqt'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_message_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi xabar yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('electrician', 'Elektrik'), ('seller', 'Sotuvchi')], max_length=20, null=True),
        ),
    ]
