# Generated by Django 5.0.1 on 2025-12-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_broadcastmessage_options_alter_gift_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Rasm')),
                ('date', models.DateField(verbose_name='Sana')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, help_text="Kichikroq raqam yuqorida ko'rsatiladi", verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Aksiya',
                'verbose_name_plural': 'Aksiyalar',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_promot_is_acti_2b8f6c_idx')],
            },
        ),
    ]
