# Generated by Django 5.0.1 on 2025-12-09 01:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('electrician', 'Elektrik (E-)'), ('seller', 'Sotuvchi (D-)')], max_length=20, verbose_name='QR-kod turi')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miqdori')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ballar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='qrcodes/generations/', verbose_name='ZIP fayl')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_generations', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
                ('qr_codes', models.ManyToManyField(blank=True, related_name='generations', to='core.qrcode', verbose_name='QR-kodlar')),
            ],
            options={
                'verbose_name': 'QR-kod generatsiyasi',
                'verbose_name_plural': 'QR-kod generatsiyalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_qrcode_status_a39d79_idx')],
            },
        ),
    ]
