# Generated by Django 5.0.1 on 2025-12-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_qrcodegeneration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-generated_at'], 'permissions': [('view_qrcode_detail', 'Can view QR code details')], 'verbose_name': 'QR-kod', 'verbose_name_plural': 'QR-kodlar'},
        ),
    ]
