# Generated by Django 5.0.1 on 2025-12-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_qrcode_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_uz_latin', models.TextField(verbose_name="Kontent (O'zbek lotin)")),
                ('content_uz_cyrillic', models.TextField(blank=True, verbose_name="Kontent (O'zbek kirill)")),
                ('content_ru', models.TextField(blank=True, verbose_name='Kontent (Ruscha)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Maxfiylik siyosati',
                'verbose_name_plural': 'Maxfiylik siyosati',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='qrcodescanattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='qrcodescanattempt',
            name='is_successful',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='qrcodescanattempt',
            index=models.Index(fields=['user', 'attempted_at', 'is_successful'], name='qrscan_user_date_success_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescanattempt',
            index=models.Index(fields=['-attempted_at'], name='qrscan_attempted_at_idx'),
        ),
    ]
