# Generated by Django 5.0.1 on 2025-12-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_privacypolicy_alter_qrcodescanattempt_attempted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qrcodescanattempt',
            name='qrscan_user_date_success_idx',
        ),
        migrations.RemoveIndex(
            model_name='qrcodescanattempt',
            name='qrscan_attempted_at_idx',
        ),
        migrations.AlterField(
            model_name='qrcodescanattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qrcodescanattempt',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
