# Generated by Django 5.0.1 on 2025-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_qrcodescanattempt_qrscan_user_date_success_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='Maxfiylik siyosatiga rozilik'),
        ),
    ]
