# Generated by Django 5.0.1 on 2025-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_telegramuser_privacy_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'permissions': [('send_region_messages', 'Can send messages to users by region')], 'verbose_name': 'Telegram foydalanuvchi', 'verbose_name_plural': 'Telegram foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='content_uz_cyrillic',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz_latin', "O'zbek (Lotin)"), ('ru', 'Русский')], default='uz_latin', max_length=15, verbose_name='Til'),
        ),
    ]
