# Generated by Django 5.0.1 on 2025-12-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_telegramuser_privacy_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-generated_at'], 'permissions': [('view_qrcode_detail', 'Can view QR code details'), ('generate_qrcodes', 'Can generate QR codes')], 'verbose_name': 'QR-kod', 'verbose_name_plural': 'QR-kodlar'},
        ),
    ]
