# Generated by Django 5.0.1 on 2025-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['region', 'district', '-created_at'], 'permissions': [('send_region_messages', 'Can send messages to users by region')], 'verbose_name': 'Telegram foydalanuvchi', 'verbose_name_plural': 'Telegram foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Viloyat'),
        ),
    ]
