# Generated by Django 5.0.1 on 2025-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_telegramuser_options_telegramuser_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code_type',
            field=models.CharField(choices=[('electrician', 'Elektrik (E)'), ('seller', 'Sotuvchi (D)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcodegeneration',
            name='code_type',
            field=models.CharField(choices=[('electrician', 'Elektrik (E)'), ('seller', 'Sotuvchi (D)')], max_length=20, verbose_name='QR-kod turi'),
        ),
    ]
