# Generated by Django 5.0.1 on 2025-12-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_privacypolicy_pdf_fields'),
        ('core', '0013_alter_qrcode_code_type_and_more'),
    ]

    operations = [
    ]
