# Generated by Django 5.0.1 on 2025-12-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20251221_2328'),
    ]

    operations = [
        # Удаляем только поля, которые были добавлены в 0012
        migrations.RemoveField(
            model_name='privacypolicy',
            name='pdf_ru',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='pdf_uz_latin',
        ),
        # content_uz_cyrillic и pdf_uz_cyrillic уже не существуют, поэтому не удаляем их
        migrations.AlterField(
            model_name='privacypolicy',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Kontent (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content_uz_latin',
            field=models.TextField(verbose_name="Kontent (O'zbek lotin)"),
        ),
    ]
