# Generated by Django 5.0.1 on 2025-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_giftredemption_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftredemption',
            name='status',
            field=models.CharField(choices=[('pending', "So'rov qabul qilindi"), ('approved', 'Mahsulot tayyorlash bosqichida'), ('sent', 'Mahsulot yetkazib berish xizmatiga topshirildi'), ('completed', 'Mahsulotni qabul qilganingizni tasdiqlang'), ('rejected', "So'rov bekor qilindi (administrator bilan bog'laning)")], default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
