# Generated by Django 5.0.1 on 2026-01-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_admin_contact_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xabarlar yuborish', 'verbose_name_plural': 'Xabarlar yuborish'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['points_cost', 'name_uz_latin'], 'verbose_name': 'Sovg‘a', 'verbose_name_plural': 'Sovg‘alar ro‘yxati'},
        ),
        migrations.AlterModelOptions(
            name='giftredemption',
            options={'ordering': ['-requested_at'], 'permissions': [('change_status_call_center', 'Call Center: Can change redemption status'), ('change_status_agent', 'Agent: Can change redemption status (sent/completed only)')], 'verbose_name': 'Sovg‘a olish uchun arizalar', 'verbose_name_plural': 'Sovg‘a olish uchun arizalar'},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-generated_at'], 'permissions': [('view_qrcode_detail', 'Can view QR code details'), ('generate_qrcodes', 'Can generate QR codes')], 'verbose_name': 'Promo-kod tarixi', 'verbose_name_plural': 'Promo-kodlar tarixi'},
        ),
        migrations.AlterModelOptions(
            name='qrcodegeneration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promo-kod yaratilish tarixi', 'verbose_name_plural': 'Promo-kodlar yaratish tarixi'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['region', 'district', '-created_at'], 'permissions': [('send_region_messages', 'Can send messages to users by region'), ('change_user_type_call_center', 'Call Center: Can change user type')], 'verbose_name': 'Telegram foydalanuvchisi', 'verbose_name_plural': 'Telegram foydalanuvchilari'},
        ),
        migrations.RenameIndex(
            model_name='gift',
            new_name='core_gift_user_ty_d0e00a_idx',
            old_name='core_gift_user_ty_7a8b2d_idx',
        ),
    ]
