# Generated by Django 5.0.1 on 2026-01-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_video_instruction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['order', 'points_cost', 'name_uz_latin'], 'verbose_name': 'Sovg‘a', 'verbose_name_plural': 'Sovg‘alar ro‘yxati'},
        ),
        migrations.AddField(
            model_name='historicalgift',
            name='order',
            field=models.IntegerField(default=0, help_text="Kichikroq raqam yuqorida ko'rsatiladi", verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
