# Generated by Django 5.0.1 on 2026-02-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_gift_options_historicalgift_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='smartup_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='SmartUP ID'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='smartup_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='SmartUP ID'),
        ),
        migrations.CreateModel(
            name='SmartUPId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_value', models.IntegerField(db_index=True, unique=True, verbose_name='SmartUP ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'SmartUP ID',
                'verbose_name_plural': 'SmartUP IDlar',
                'ordering': ['id_value'],
                'indexes': [models.Index(fields=['id_value'], name='core_smartu_id_valu_7d2777_idx')],
            },
        ),
    ]
