# Generated by Django 5.0.1 on 2026-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_video_instruction_4_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftredemption',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='historicalgiftredemption',
            name='processed_at',
        ),
        migrations.AddField(
            model_name='historicalbroadcastmessage',
            name='image',
            field=models.TextField(blank=True, help_text="Ixtiyoriy. Rasm qo'shilsa, xabar caption sifatida yuboriladi. HTML formatlash va havolalar qo'llab-quvvatlanadi.", max_length=100, null=True, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='historicalpromotion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='file_id_electrician_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id Elektrik RU'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='file_id_electrician_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id Elektrik UZ'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='file_id_seller_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id Tadbirkor RU'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='file_id_seller_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file_id Tadbirkor UZ'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='thumb_electrician_ru',
            field=models.TextField(blank=True, help_text='JPEG, max 320x320, 200KB. Превью для видео.', max_length=100, null=True, verbose_name='Thumbnail — Elektrik (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='thumb_electrician_uz',
            field=models.TextField(blank=True, help_text="JPEG, max 320x320, 200KB. Oldindan ko'rinish uchun.", max_length=100, null=True, verbose_name="Thumbnail — Elektrik (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='thumb_seller_ru',
            field=models.TextField(blank=True, help_text='JPEG, max 320x320, 200KB.', max_length=100, null=True, verbose_name='Thumbnail — Tadbirkor (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='thumb_seller_uz',
            field=models.TextField(blank=True, help_text='JPEG, max 320x320, 200KB.', max_length=100, null=True, verbose_name="Thumbnail — Tadbirkor (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='video_electrician_ru',
            field=models.TextField(blank=True, help_text='Video fayl elektriklar uchun rus tilida', max_length=100, null=True, verbose_name='Video — Elektrik (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='video_electrician_uz',
            field=models.TextField(blank=True, help_text="Video fayl elektriklar uchun o'zbek tilida", max_length=100, null=True, verbose_name="Video — Elektrik (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='video_seller_ru',
            field=models.TextField(blank=True, help_text='Video fayl tadbirkorlar uchun rus tilida', max_length=100, null=True, verbose_name='Video — Tadbirkor (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='historicalvideoinstruction',
            name='video_seller_uz',
            field=models.TextField(blank=True, help_text="Video fayl tadbirkorlar uchun o'zbek tilida", max_length=100, null=True, verbose_name="Video — Tadbirkor (O'zbek)"),
        ),
    ]