# Generated by Django 5.0.1 on 2026-03-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_region_message_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='promo_block_stage',
            field=models.IntegerField(default=0, verbose_name='Promokod bloklash bosqichi (0 — yo‘q, 1 — 5 daqiqa, 2 — 1 kun, 3 — cheksiz)'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='promo_blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Promokod kiritishni bloklash tugash vaqti'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='promo_failed_attempts',
            field=models.IntegerField(default=0, verbose_name='Noto‘g‘ri promokod urinishlari (ketma-ket)'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='promo_block_stage',
            field=models.IntegerField(default=0, verbose_name='Promokod bloklash bosqichi (0 — yo‘q, 1 — 5 daqiqa, 2 — 1 kun, 3 — cheksiz)'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='promo_blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Promokod kiritishni bloklash tugash vaqti'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='promo_failed_attempts',
            field=models.IntegerField(default=0, verbose_name='Noto‘g‘ri promokod urinishlari (ketma-ket)'),
        ),
        migrations.CreateModel(
            name='PromoCodeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(blank=True, help_text='Foydalanuvchi kiritgan asl matn (kod mavjud bo‘lmasligi mumkin)', max_length=255, verbose_name='Kiritilgan promokod')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Urinish vaqti')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Muvaffaqiyatli')),
                ('source', models.CharField(choices=[('bot', 'Telegram bot'), ('webapp', 'Telegram Web App'), ('unknown', 'Unknown')], default='unknown', help_text='Qayerdan kiritilgan: bot yoki Web App', max_length=20, verbose_name='Manba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_attempts', to='core.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Promokod urinishlari',
                'verbose_name_plural': 'Promokod urinishlari',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['attempted_at'], name='core_promoc_attempt_f0b59d_idx'), models.Index(fields=['source'], name='core_promoc_source_860f77_idx'), models.Index(fields=['is_successful'], name='core_promoc_is_succ_e43629_idx')],
            },
        ),
    ]
