# Generated by Django 5.0.1 on 2026-03-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_historicaltelegramuser_promo_block_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltelegramuser',
            name='promo_block_stage',
            field=models.IntegerField(default=0, verbose_name='Promokod bloklash bosqichi (0 — yo‘q, 3 — faqat eski cheksiz blok)'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='promo_block_stage',
            field=models.IntegerField(default=0, verbose_name='Promokod bloklash bosqichi (0 — yo‘q, 3 — faqat eski cheksiz blok)'),
        ),
    ]
