# Generated by Django 5.0.1 on 2026-04-17 13:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_monthlypromoparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_redemptions', to='core.telegramuser', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='historicalbroadcastmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='historicalgiftredemption',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.telegramuser', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='historicalqrcodegeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='qrcodegeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='regionmessagelog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalMonthlyPromoParticipant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('month', models.DateField(db_index=True, verbose_name='Oy (1-kun)')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='Tartib raqami (oy bo‘yicha)')),
                ('first_promo_at', models.DateTimeField(verbose_name='Birinchi promokod vaqti')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.telegramuser', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'historical Monthly promo participant',
                'verbose_name_plural': 'historical Monthly promo participants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
