# Generated by Django 5.0.1 on 2026-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_historicalmonthlypromoparticipant_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlypromoparticipant',
            options={'ordering': ['-month', 'user_type', 'order'], 'verbose_name': 'Monthly promo participant', 'verbose_name_plural': 'Monthly promo participants'},
        ),
        migrations.AlterField(
            model_name='historicalmonthlypromoparticipant',
            name='user_type',
            field=models.CharField(choices=[('electrician', 'Elektrik'), ('seller', 'Sotuvchi')], db_index=True, default='electrician', max_length=20, verbose_name='Foydalanuvchi turi'),
            preserve_default=False,
        ),
    ]