# Generated by Django 5.0.1 on 2026-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_monthlypromoparticipant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmessagelog',
            name='image_storage_path',
            field=models.CharField(blank=True, help_text='Относительный путь в default_storage; используется для отложенной рассылки.', max_length=500, verbose_name='Путь к фото'),
        ),
        migrations.AddField(
            model_name='regionmessagelog',
            name='message_text',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
        migrations.AddField(
            model_name='regionmessagelog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Время отправки для отложенной рассылки.', null=True, verbose_name='Запланирована на'),
        ),
        migrations.AlterField(
            model_name='regionmessagelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=20),
        ),
    ]
