# Generated by Django 5.0.1 on 2026-04-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_region_message_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(db_index=True, help_text='Уникальный ключ месяца — защита от двойного запуска.', max_length=7, unique=True, verbose_name='Месяц (YYYY-MM)')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='running', max_length=20, verbose_name='Статус')),
                ('total', models.IntegerField(default=0, verbose_name='Всего получателей')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Ежемесячное напоминание (лог)',
                'verbose_name_plural': 'Ежемесячное напоминание (логи)',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Если выключено — рассылка не выполняется.', verbose_name='Включено')),
                ('time_of_day', models.TimeField(default='10:00', help_text='Локальное время (Asia/Tashkent), 1-го числа каждого месяца.', verbose_name='Время отправки')),
                ('text_uz_latin', models.TextField(help_text='Поддерживается HTML: <b>, <i>, <a href>. По умолчанию для пользователей с языком uz_latin или без указанного языка.', verbose_name='Текст (uz_latin)')),
                ('text_ru', models.TextField(help_text='Поддерживается HTML. Для пользователей с языком ru.', verbose_name='Текст (ru)')),
                ('image', models.ImageField(blank=True, help_text='Если загружена — текст идёт как подпись к фото.', null=True, upload_to='monthly_reminders/', verbose_name='Картинка (опционально)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Ежемесячное напоминание (настройки)',
                'verbose_name_plural': 'Ежемесячное напоминание (настройки)',
            },
        ),
    ]
