# Generated by Django 5.0.1 on 2026-04-25 13:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_monthly_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypromoparticipant',
            name='user',
        ),
        migrations.CreateModel(
            name='HistoricalMonthlyPromoTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('month', models.DateField(db_index=True, verbose_name='Oy (1-kun)')),
                ('user_type', models.CharField(choices=[('electrician', 'Elektrik'), ('seller', 'Sotuvchi')], db_index=True, max_length=20, verbose_name='Foydalanuvchi turi')),
                ('order', models.PositiveIntegerField(db_index=True, help_text='Порядковый номер билета внутри (месяц, user_type).', verbose_name='Bilet № (oy bo‘yicha)')),
                ('scanned_at', models.DateTimeField(verbose_name='Skanerlash vaqti')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.qrcode', verbose_name='QR-promokod')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.telegramuser', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'historical Monthly promo ticket',
                'verbose_name_plural': 'historical Monthly promo tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MonthlyPromoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, verbose_name='Oy (1-kun)')),
                ('user_type', models.CharField(choices=[('electrician', 'Elektrik'), ('seller', 'Sotuvchi')], db_index=True, max_length=20, verbose_name='Foydalanuvchi turi')),
                ('order', models.PositiveIntegerField(db_index=True, help_text='Порядковый номер билета внутри (месяц, user_type).', verbose_name='Bilet № (oy bo‘yicha)')),
                ('scanned_at', models.DateTimeField(verbose_name='Skanerlash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_ticket', to='core.qrcode', verbose_name='QR-promokod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_promo_tickets', to='core.telegramuser', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Monthly promo ticket',
                'verbose_name_plural': 'Monthly promo tickets',
                'ordering': ['-month', 'user_type', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='HistoricalMonthlyPromoParticipant',
        ),
        migrations.DeleteModel(
            name='MonthlyPromoParticipant',
        ),
        migrations.AddIndex(
            model_name='monthlypromoticket',
            index=models.Index(fields=['month', 'user'], name='idx_ticket_month_user'),
        ),
        migrations.AddConstraint(
            model_name='monthlypromoticket',
            constraint=models.UniqueConstraint(fields=('month', 'user_type', 'order'), name='uniq_monthly_ticket_order_per_type'),
        ),
    ]
