# Generated by Django 5.0.1 on 2026-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_live_streams'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livestream',
            new_name='core_livest_is_acti_9b4cf9_idx',
            old_name='core_livest_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='livestreamwinner',
            new_name='core_livest_live_st_c3838e_idx',
            old_name='core_livest_live_st_pos_idx',
        ),
        migrations.AlterField(
            model_name='monthlyremindersettings',
            name='text_uz_latin',
            field=models.TextField(help_text='Поддерживается HTML: &lt;b&gt;, &lt;i&gt;, &lt;a href&gt;. По умолчанию для пользователей с языком uz_latin или без указанного языка.', verbose_name='Текст (uz_latin)'),
        ),
    ]
