# Generated by Django 5.0.1 on 2026-04-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_rename_core_livest_is_acti_idx_core_livest_is_acti_9b4cf9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallivestream',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='cover',
        ),
    ]
