/**
 * build_admin_spa.js
 * JSX → JS: Admin SPA fayllarini esbuild bilan compile qilish
 * Barcha JSX fayllarini bitta bundle.js ga yig'adi
 *
 * Ishlatish: node scripts/build_admin_spa.js
 */

const fs   = require('fs');
const path = require('path');

// esbuild — Vite dependency sifatida o'rnatilgan
let esbuild;
try {
  esbuild = require(path.join(__dirname, '..', 'frontend', 'node_modules', 'esbuild'));
} catch(e) {
  try {
    esbuild = require('esbuild');
  } catch(e2) {
    console.error('esbuild topilmadi: ' + e.message);
    process.exit(1);
  }
}

const SPA_DIR = path.join(__dirname, '..', 'core', 'static', 'admin_ui', 'spa');

// Load order matters — later files can use globals from earlier files
const JSX_FILES = [
  'tweaks-panel',
  'ui',
  'shell',
  'pages-core',
  'pages-qr',
  'pages-comm',
  'pages-meta',
  'app',
];

// ── Step 1: also compile individual files (for backward compat) ──
let individualSuccess = 0;
let individualErrors  = 0;

for (const name of JSX_FILES) {
  const inFile  = path.join(SPA_DIR, name + '.jsx');
  const outFile = path.join(SPA_DIR, name + '.js');

  try {
    const source = fs.readFileSync(inFile, 'utf8');
    const result = esbuild.transformSync(source, {
      loader:      'jsx',
      jsxFactory:  'React.createElement',
      jsxFragment: 'React.Fragment',
      target:      'es2017',
    });
    fs.writeFileSync(outFile, result.code);
    console.log(`  ✓  ${name}.jsx  →  ${name}.js`);
    individualSuccess++;
  } catch (err) {
    console.error(`  ✗  ${name}.jsx  XATO: ${err.message}`);
    individualErrors++;
  }
}

// ── Step 2: bundle ALL JSX into single bundle.js ──
console.log('\n  Bundling all JSX into bundle.js...');

try {
  // Concatenate all JSX files in order with clear section separators
  let combined = '// AUTO-GENERATED: all SPA JSX files bundled together\n// DO NOT EDIT — regenerated by scripts/build_admin_spa.js\n\n';

  for (const name of JSX_FILES) {
    const inFile = path.join(SPA_DIR, name + '.jsx');
    const source = fs.readFileSync(inFile, 'utf8');
    combined += `\n// ============================================================\n`;
    combined += `// FILE: ${name}.jsx\n`;
    combined += `// ============================================================\n`;
    combined += source;
    combined += '\n';
  }

  const result = esbuild.transformSync(combined, {
    loader:      'jsx',
    jsxFactory:  'React.createElement',
    jsxFragment: 'React.Fragment',
    target:      'es2017',
  });

  const bundleOut = path.join(SPA_DIR, 'bundle.js');
  fs.writeFileSync(bundleOut, result.code);
  const sizeKb = Math.round(result.code.length / 1024);
  console.log(`  ✓  bundle.js  (${sizeKb} KB)`);
} catch (err) {
  console.error(`  ✗  bundle.js  XATO: ${err.message}`);
  individualErrors++;
}

console.log(`\nNatija: ${individualSuccess + (individualErrors === 0 ? 1 : 0)} muvaffaqiyatli, ${individualErrors} xato`);
if (individualErrors > 0) process.exit(1);
